spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: root
server:
  port: 8586
mybatis:
  type-aliases-package: com.sean.webcrawler.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    org.springframework.web: ERROR
    com.sean: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{18} - %msg%n"
  file:
    name: mylog.log
    path: ./
    max-size: 20MB